# Pre-reqs
# 1. install dl-rake-latex gem
# 2. install graffle gem
# 3. read tutorial for using dl-rake-latex > 
#    http://devel.softeng.ox.ac.uk/trac/softeng/wiki/Utilities/RakeLatex
#
# Basic usage:
# The basic usage is to place a Rakefile.rb file in the same directory as your LaTeX source, and to 
# place the appropriate rake task definitions into this rakefile. Once this is done, you can generate 
# DVI, PS, and PDF output, respectively, using the following commands:
#
#   rake dvi
#   rake ps
#   rake pdf
#
# Usage Scenarios
#
# 1. Single document
# The simplest case is that you have a directory containing a single LaTeX document, which has no 
# dependencies on other LaTeX files, figures, or bibliography files. For example, you might have the 
# following directory structure:
#   mydoc/
#       Rakefile.rb
#       mydoc.tex
#
# The contents of Rakefile.rb should be:
#   require 'rake-latex'
#   Rake.startfile(__FILE__)
#       # LaTeX document in mydoc.tex.
#       latex('mydoc')
#
#   Rake.endfile
#
# 2. Single document, no references
# The default LaTeX task generated by the previous example assumes that there are references in the 
# document, and that LaTeX needs to be run twice in order to generate and use the correct mydoc.aux 
# file. If you know that your document contains no references, and want to speed up the generation 
# process by only running LaTeX once, you can modify the properties of the LaTeX task as follows:
# 
#   require 'rake-latex'
#   Rake.startfile(__FILE__)
#       latex('mydoc') do
#           |task|
#           task.need_aux = false
#       end
#   Rake.endfile
#
# 3. Single document, with bibliography ¶
# If you have citations in your document, you will probably have a BibTeX file floating around somewhere
# containing the references. For instance, you might have:
#
#   myrefs/
#       refs.bib
#   mydoc/
#       Rakefile.rb
#       mydoc.tex
# **Note** Notice how the references file does not have to be in the same directory as the LaTeX file!!
#
# The rakefile then becomes:
#    require 'rake-latex'
#    Rake.startfile(__FILE__)
#       latex('mydoc') do
#           |task|
#           task.references = ['../myrefs/refs.bib']
#       end
#    Rake.endfile
#
#  When you run rake pdf, this will execute four commands, giving you a PDF with all references and 
#  citations correct:
#
#   1. pdflatex
#   2. bibtex
#   3. pdflatex
#   4. pdflatex
#
#  TODO(Huascar) describe the scenarios where images are included...
#
#

require 'rake-latex'

Rake.startfile(__FILE__)

# LaTeX document => report.tex with bibliography citations.
latex('report') do
    |task|
    task.references = ['report.bib']
    task.includes = [
        'introduction.tex',
        'relatedwork.tex',
        'system.tex',
        'conclusions.tex',
        'futurework.tex',
        'problemdescription.tex',
        'algorithms.tex',
        'architecture.tex',
        'demo.tex',
        'three.tex'
    ]
end

Rake.endfile
